"""Curated, evidence-qualified history of experimental chiral-phonon research."""

EVIDENCE_LEVELS = {
    "Direct mode-resolved": "Momentum or polarization resolves the phonon handedness itself.",
    "Spectroscopic identification": "Selection rules plus modelling identify a rotational or chiral mode.",
    "Driven response": "A circular phonon is coherently driven and its magnetic or electronic effect is measured.",
    "Angular-momentum coupling": "A chiral lattice channel is identified through selective coupling or transfer.",
}


MATERIAL_SYSTEMS = [
    {
        "material": "Monolayer WSe₂",
        "family": "2D transition-metal dichalcogenide",
        "year": 2018,
        "evidence": "Spectroscopic identification",
        "method": "Helicity-resolved ultrafast spectroscopy",
        "finding": "Valley-selective intervalley scattering supplied the first experimental identification of zone-corner phonon pseudo-angular momentum.",
        "caveat": "A K/K′ circular mode; later work distinguishes this valley usage from true 3D dynamical chirality.",
        "url": "https://doi.org/10.1126/science.aar2711",
    },
    {
        "material": "α-HgS (cinnabar)",
        "family": "3D chiral crystal",
        "year": 2022,
        "evidence": "Spectroscopic identification",
        "method": "Circularly polarized Raman + first principles",
        "finding": "Opposite enantiomorphs showed propagating, rotating modes with opposite pseudo-angular momentum and group velocity.",
        "caveat": "Identification combines Raman selection rules with calculated dispersion, PAM and angular momentum.",
        "url": "https://doi.org/10.1038/s41567-022-01790-x",
    },
    {
        "material": "α-quartz (SiO₂)",
        "family": "3D chiral crystal",
        "year": 2023,
        "evidence": "Direct mode-resolved",
        "method": "Circular-polarization RIXS + DFT",
        "finding": "Circular dichroism mapped chiral phonon dispersion at finite momentum in opposite quartz enantiomorphs.",
        "caveat": "A direct probe of lattice chirality–locked phonons, not a measurement of a macroscopic phonon-induced effect.",
        "url": "https://doi.org/10.1038/s41586-023-06016-5",
    },
    {
        "material": "FePSe₃",
        "family": "Layered antiferromagnet",
        "year": 2023,
        "evidence": "Angular-momentum coupling",
        "method": "Magneto-infrared and polarization-resolved Raman",
        "finding": "Chirality-selective magnon–phonon hybridization produced paired magnon polarons and magnon-induced chiral phonons.",
        "caveat": "Evidence concerns angular-momentum-selective hybridization in a magnetic material, not structural chirality.",
        "url": "https://doi.org/10.1038/s41467-023-39123-y",
    },
    {
        "material": "CeF₃",
        "family": "Rare-earth halide paramagnet",
        "year": 2023,
        "evidence": "Driven response",
        "method": "Circular THz pump + magneto-optical probe",
        "finding": "Coherently driven circular phonons polarized Ce 4f moments, yielding a large transient effective magnetic field.",
        "caveat": "The measured result is a phonon-driven spin response; it is not finite-q imaging of phonon chirality.",
        "url": "https://doi.org/10.1126/science.adi9601",
    },
    {
        "material": "SrTiO₃",
        "family": "Quantum paraelectric perovskite",
        "year": 2024,
        "evidence": "Driven response",
        "method": "Polarization-shaped THz pump + magneto-optics",
        "finding": "Orthogonal soft-mode components generated rotating polarization and room-temperature transient magnetization.",
        "caveat": "A zone-centre circular polar mode and dynamical-multiferroic response; not a propagating truly chiral phonon.",
        "url": "https://doi.org/10.1038/s41586-024-07175-9",
    },
    {
        "material": "Elemental tellurium",
        "family": "Chiral elemental semiconductor",
        "year": 2025,
        "evidence": "Direct mode-resolved",
        "method": "Thermal-gradient mechanical torque",
        "finding": "A chirality-dependent macroscopic torque measured thermally generated phonon angular momentum.",
        "caveat": "Direct angular-momentum evidence; the later momentum-resolved scattering experiment resolves the modes themselves.",
        "url": "https://doi.org/10.1038/s41567-025-02952-3",
    },
    {
        "material": "LiNbO₃",
        "family": "Polar ferroelectric oxide",
        "year": 2025,
        "evidence": "Direct mode-resolved",
        "method": "Circular-polarization RIXS + DFT",
        "finding": "Finite-momentum circular dichroism directly established chiral phonons in a polar, non-chiral crystal.",
        "caveat": "Shows inversion breaking, not a chiral space group, can support momentum-dependent phonon angular momentum.",
        "url": "https://doi.org/10.1038/s41467-025-66911-5",
    },
    {
        "material": "ErFeO₃",
        "family": "Rare-earth orthoferrite",
        "year": 2017,
        "evidence": "Driven response",
        "method": "Phase-controlled mid-IR excitation + Faraday rotation",
        "finding": "Simultaneous excitation of orthogonal IR modes generated elliptical ionic motion and coherent spin precession.",
        "caveat": "The modes are non-degenerate and the magnetic field is inferred from the spin response and modelling.",
        "url": "https://doi.org/10.1038/nphys3925",
        "papers": [
            ("Journal article", "https://doi.org/10.1038/nphys3925"),
            ("arXiv:1512.06351", "https://arxiv.org/abs/1512.06351"),
        ],
    },
    {
        "material": "Bi₂Se₃",
        "family": "Layered topological insulator",
        "year": 2026,
        "evidence": "Direct mode-resolved",
        "method": "Circular THz pump + polarization-resolved THz Kerr detection",
        "finding": "Phase-resolved orthogonal Raman coordinates reconstructed phonon-to-phonon angular-momentum transfer.",
        "caveat": "This is a coherently prepared rotating state and rotational Umklapp, not an intrinsic finite-q chiral eigenmode.",
        "url": "https://doi.org/10.1038/s41567-026-03274-8",
        "papers": [
            ("Nature Physics article", "https://doi.org/10.1038/s41567-026-03274-8"),
        ],
    },
    {
        "material": "GdFeCo on sapphire/glass",
        "family": "Magnetic film / phononic substrate heterostructure",
        "year": 2024,
        "evidence": "Driven response",
        "method": "Circular mid-IR substrate excitation + magnetic-domain imaging",
        "finding": "Circular substrate phonons produced helicity-dependent permanent switching in an adjacent magnetic film.",
        "caveat": "The relevant phonons belong to the substrate; the magnetic layer is controlled non-locally.",
        "url": "https://doi.org/10.1038/s41586-024-07200-x",
        "papers": [
            ("Nature article", "https://doi.org/10.1038/s41586-024-07200-x"),
            ("arXiv:2305.11551", "https://arxiv.org/abs/2305.11551"),
        ],
    },
    {
        "material": "BPO₄",
        "family": "Non-chiral tetragonal oxide",
        "year": 2025,
        "evidence": "Driven response",
        "method": "Resonant high-frequency THz pump + full optical polarimetry",
        "finding": "Selective excitation of a degenerate mode created switchable transient ferrichiral crystal structures.",
        "caveat": "Structural chirality control; it does not by itself establish a phonon magnetic moment or propagating chiral eigenmode.",
        "url": "https://doi.org/10.1126/science.adr4713",
    },
    {
        "material": "SrRuO₃/SrTiO₃ heterostructures",
        "family": "Magnetic oxide superlattice",
        "year": 2024,
        "evidence": "Angular-momentum coupling",
        "method": "Ultrafast demagnetization + time-resolved magneto-optics",
        "finding": "Thickness-dependent delayed dynamics supported spin angular-momentum transfer into acoustic chiral phonons.",
        "caveat": "The phonon population is generated by spin loss rather than a circular THz pump.",
        "url": "https://doi.org/10.1038/s41565-024-01719-w",
    },
]


LANDMARKS = [
    {
        "year": 2014,
        "stage": "Foundation",
        "title": "Angular Momentum of Phonons and the Einstein–de Haas Effect",
        "why": "Established a microscopic phonon-angular-momentum framework and connected it to macroscopic rotation.",
        "url": "https://doi.org/10.1103/PhysRevLett.112.085503",
        "material": "General theory",
        "kind": "Theory",
    },
    {
        "year": 2015,
        "stage": "Valley chirality",
        "title": "Chiral Phonons at High-Symmetry Points in Monolayer Hexagonal Lattices",
        "why": "Introduced valley phonon pseudo-angular momentum and helicity-dependent selection rules.",
        "url": "https://doi.org/10.1103/PhysRevLett.115.115502",
        "material": "Monolayer hexagonal lattices",
        "kind": "Theory",
    },
    {
        "year": 2017,
        "stage": "Driven circular motion",
        "title": "Dynamical multiferroicity",
        "why": "Formalized magnetization generated by time-dependent, rotating electric polarization.",
        "url": "https://doi.org/10.1103/PhysRevMaterials.1.014401",
        "material": "Polar solids",
        "kind": "Theory",
    },
    {
        "year": 2017,
        "stage": "Ultrafast control",
        "title": "An effective magnetic field from optically driven phonons",
        "why": "Connected coherently driven ionic loops to a magnetic field and nonlinear phononics.",
        "url": "https://doi.org/10.1038/nphys3925",
        "material": "ErFeO₃",
        "kind": "Experiment + modelling",
    },
    {
        "year": 2018,
        "stage": "First experimental identification",
        "title": "Observation of chiral phonons",
        "why": "Used helicity-dependent intervalley scattering to identify zone-corner phonon PAM.",
        "url": "https://doi.org/10.1126/science.aar2711",
        "material": "Monolayer WSe₂",
        "kind": "Experiment",
    },
    {
        "year": 2019,
        "stage": "Spin-to-lattice transfer",
        "title": "The ultrafast Einstein–de Haas effect",
        "why": "Tracked ultrafast angular-momentum transfer from spins into circular lattice motion and strain.",
        "url": "https://doi.org/10.1038/s41586-018-0822-7",
        "material": "Ferromagnetic iron",
        "kind": "Experiment",
    },
    {
        "year": 2022,
        "stage": "True dynamical chirality",
        "title": "Truly chiral phonons in α-HgS",
        "why": "Distinguished propagating 3D chiral modes from merely circular zone-centre or valley motion.",
        "url": "https://doi.org/10.1038/s41567-022-01790-x",
        "material": "α-HgS",
        "kind": "Experiment + theory",
    },
    {
        "year": 2023,
        "stage": "Momentum-resolved proof",
        "title": "Chiral phonons in quartz probed by X-rays",
        "why": "Mapped handed phonon dispersion at general momenta using circularly polarized RIXS.",
        "url": "https://doi.org/10.1038/s41586-023-06016-5",
        "material": "α-quartz",
        "kind": "Experiment",
    },
    {
        "year": 2023,
        "stage": "Spin–lattice hybridization",
        "title": "Chirality-selective magnon–phonon hybridization in FePSe₃",
        "why": "Resolved angular-momentum-selective coupling between magnons and nearly degenerate phonons.",
        "url": "https://doi.org/10.1038/s41467-023-39123-y",
        "material": "FePSe₃",
        "kind": "Experiment",
    },
    {
        "year": 2023,
        "stage": "THz phonomagnetism",
        "title": "Large effective magnetic fields from chiral phonons in rare-earth halides",
        "why": "Demonstrated a sizeable transient spin polarization driven by circular THz lattice motion.",
        "url": "https://doi.org/10.1126/science.adi9601",
        "material": "CeF₃",
        "kind": "Experiment",
    },
    {
        "year": 2024,
        "stage": "Dynamical multiferroicity observed",
        "title": "Terahertz electric-field-driven dynamical multiferroicity in SrTiO₃",
        "why": "Measured room-temperature magnetization from coherently rotating polar soft modes.",
        "url": "https://doi.org/10.1038/s41586-024-07175-9",
        "material": "SrTiO₃",
        "kind": "Experiment",
    },
    {
        "year": 2025,
        "stage": "Macroscopic angular momentum",
        "title": "Measurement of phonon angular momentum",
        "why": "Detected enantiomer-dependent mechanical torque under a thermal gradient.",
        "url": "https://doi.org/10.1038/s41567-025-02952-3",
        "material": "Tellurium",
        "kind": "Experiment",
    },
    {
        "year": 2025,
        "stage": "Polar-material expansion",
        "title": "Chiral phonons in polar LiNbO₃",
        "why": "Directly demonstrated finite-momentum chiral phonons in a polar but non-chiral crystal.",
        "url": "https://doi.org/10.1038/s41467-025-66911-5",
        "material": "LiNbO₃",
        "kind": "Experiment",
    },
    {
        "year": 2026,
        "stage": "Mode-resolved verification",
        "title": "Momentum-Resolved Direct Observation of Chiral Phonons in Elemental Tellurium",
        "why": "Connected momentum-resolved scattering to circular acoustic eigenvectors in a chiral crystal.",
        "url": "https://doi.org/10.1103/5cks-j4ht",
        "material": "Tellurium",
        "kind": "Experiment",
    },
]


CONCEPT_STAGES = [
    ("Angular momentum", "Can lattice vibrations carry real angular momentum?"),
    ("Valley PAM", "How do crystal symmetry and pseudo-angular momentum constrain scattering?"),
    (
        "True chirality",
        "Does a rotating mode also propagate with a handed relation between motion and momentum?",
    ),
    ("Driven response", "Can coherent THz excitation create magnetization or manipulate spins?"),
    (
        "Direct verification",
        "Can momentum, polarization, torque or angular momentum be resolved without inference alone?",
    ),
    (
        "Functionality",
        "Can handed lattice motion control spin, charge, heat, topology or ferroic domains?",
    ),
]
